###     REGISTER ERRORS

class RegisterNotImplemented (Exception): ...

class RegisterTooSmallToMove (Exception): ...

class RegisterSizeTooSmall (Exception): ...

class OperationNotPossible (Exception): ...

class RegisterCantEffectiveAddress (Exception): ...

class RegisterNotWritable (Exception): ...

###     NUMBER ERROR

class WrongNumberBase (Exception):  ...

class NumberTooBig (Exception): ...

class NumberSizeRequired (Exception): ...

class CantPushValueTooBig (Exception): ...

###     ARGUMENT ERROR

class EmptyLine (Exception): ...

class ArgumentNotExpected (Exception): 
    """
    Execution of funcion - ex. POPA - with any argument
    -> POPA 10
    -> POPA AX
    -> POPA CX, 12
    """
    ...

class NotEnoughArguments (Exception):
    """
    Occurs when trying to execute a function with not enough parameters
    """
    ...

class TooManyArgumentsToUnpack (Exception): 
    """
    Occurs when trying to execute a function with too many parameters
    """
    ...

###     OTHER ERRORS

class OperandSizeNotSpecified (Exception): ...

class EffectiveAddressError (Exception): ...

class EffectiveAddresNotExist (Exception): ...

class VariableAddressNotExisting (Exception): ...