from .arithmetic_instrunctions import *
from .flag_setting_instructions import *
from .logical_instrunctions import *
from .flow_control_instructions import *
from .jump_instructions import *
from .stack_instructions import *
from .data_movement_instructions import *
from .interrupt_instructions import *
from .bit_movement_instructions import *